name: CI

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Clarinet
      run: |
        wget -nv https://github.com/hirosystems/clarinet/releases/download/v2.9.0/clarinet-linux-x64.tar.gz -O clarinet-linux-x64.tar.gz
        tar -xf clarinet-linux-x64.tar.gz
        chmod +x ./clarinet
        echo "$(pwd)" >> $GITHUB_PATH
        
    - name: Run Clarinet Check
      run: ./clarinet check
